name: learn-github-actions
on: [push]
jobs:
  Build_PDFs:
    runs-on: ubuntu-latest
    steps:
      - name: Update packages
        run: sudo apt-get update && sudo apt-get upgrade -y

      - name: Install pandoc & fonts
        run: sudo apt-get install -y pandoc texlive-xetex texlive-fonts-extra texlive-fonts-recommended

      - name: Install Quarto
        run: |
          wget https://github.com/quarto-dev/quarto-cli/releases/download/v0.9.442/quarto-0.9.442-linux-amd64.deb
          sudo dpkg -i quarto-0.9.442-linux-amd64.deb

      - name: Install SSH Key
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          # echo "${{ secrets.KNOWN_HOSTS }}" > ~/.ssh/known_hosts

      - name: Checkout repo
        uses: actions/checkout@v3


      - name: Install Python requirements
        run: pip3 install -r requirements.txt

      - run: mkdir -p output

      - name: Run pandoc
        run: pandoc -V papersize:a4 --highlight-style breezeDark --pdf-engine xelatex -o foo.pdf foo.md

      - name: Run Quarto
        run: quarto render foo.qmd --to pdf

      - name: Mv files to output folder
        run: mv *.pdf output

      - uses: actions/upload-artifact@v3
        with:
          name: pdf_output
          path: |
            output/foo.pdf
            output/foo2.pdf

      - name: Move pdf files to server
        run: rsync  -P -a -v --recursive --cvs-exclude 'output/' -e  'ssh  -vvv -p 1022 ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:~/ci_pdf_outputs'
